export const categories = {
    keyboards: [
        "/novelkeys/i",
        "/kebo\\.store/i",
        "/cephalopodc?/i",
        "/lillekrydde/i",
        "/thekey\\.company/i",
        "/dixie mech/i",
        "/nicetechnol/i",
        "/ringerkeys\\.com/i",
        "/keyboards?/i",
        "/aliexpress/i",
        "/archetype/i",
        "/rama ?works/i",
        "/malvix/i",
        "/spacecables/i",
        "/nice technologies/i",
        "/zeal generation/i",
        "/valvik/i",
        "/zhantu huang/i",
        "/zap cables/i",
        "/(mass)?drop(\\.com)?/i",
        "/teal technik/i",
        "/originative/i",
        "/smpl supply/i",
        "/cftkb/i",
        "/unicomp, inc./i",
        "/projectkb/i",
        "/glorious pc/i",
        "/pikatea/i",
        "/\\*3334186279/i",
        "/stupidfish/i",
    ],
    shopping: [
        "/amzn mktp/i",
        "/amazon\\.com\\*/i",
        "/bestbuy/i",
        "/formd/i",
        "/target/i",
        "/indiegogo/i",
        "/dbrand/i",
        "/facebook/i",
        "/pocket-tripod-pro/i",
        "/topo designs/i",
        "/micro ?center/i",
        "/vans inc/i",
        "/dba.*chip.*off/i",
        "/ikea.com/i",
        "/ebay/i",
    ],
    games: [
        "/riot/i",
        "/origin.com/i",
        "/steam(games\\.com| purchase)/i",
        "/bumble/i",
        "/mojang/i",
        "/kinguin/i",
        "/sirvo llc/i",
        "/red apps/i",
        "/nadav fima/i",
    ],
    food: [
        "/south loop market/i",
        "/jewel osco/i",
        "/dunkin/i",
        "/h mart/i",
        "/walgreens/i",
        "/giordano'?s/i",
        "/shake shack/i",
        "/mcdonald's/i",
        "/federales/i",
        "/popeyes/i",
        "/amazon tips/i",
        "/freshly/i",
        "/uber eats/i",
        "/luke's/i",
        "/althea/i",
        "/city tap/i",
        "/vivi bubble tea/i",
        "/craft pizza/i",
        "/pepsi(ven)?/i",
        "/cescas/i",
        "/do-rite/i",
        "/california food mart/i",
        "/welcome back lounge/i",
        "/cvs\\/pharmacy/i",
        "/noodles etc/i",
        "/tikka n  curry/i",
        "/domino's/i",
        "/harold's/i",
        "/mothers chicago/i",
        "/fulton market local/i",
        "/venmo/i",
        "/teamo boba/i",
        "/sangamon chicago/i",
        "/chipotle/i",
        "/la fournette/i",
        "/vanille/i",
        "/7-eleven/i",
        "/the monkey's paw/i",
        "/1lncln prk/i",
        "/burger king/i",
        "/zelle.*to j/i",
    ],
    housing: [
        "/jin's electric/i",
        "/zelle.*to w/i",
    ],
    finances: [
        "/vanguard/i",
        "/autosave/i",
        "/dividend/i",
        "/employer contribution/i",
        "/interest/i",
        "/investment: v/i",
    ],
    fees: [
        "/foreign exchange rate adjustment/i",
        "/healthequity inc/i",
        "/domestic incoming wire fee/i",
        "/foreign transaction fee/i",
    ],
    income: [
        "/google llc/i",
        "/deposit/i",
        "/nacho/i",
        "/^tps$/i",
        "/impot solidarite/i",
        "/tax ref/i",
        "/fedwire credit/i",
        "/morgan stanley.*(credit|payment)/i",
        "/zelle.*from/i"
    ],
    subscriptions: [
        "/amazon prime/i",
        "/patreon/i",
        "/netflix\\.com/i",
        "/github/i",
        "/disney plus/i",
        "/agilebits|1password/i",
        "/n(ew )?y(ork)? times/i",
        "/average tech revi(ews)?/i",
        "/google storage?/i",
    ],
    utilities: [
        "/com(m )?ed/i",
        "/ventra/i",
        "/usps change of address?/i",
        "/google fi/i",
        "/state farm/i",
        "/hair cuttery/i",
        "/supercuts/i",
        "/bell mobility/i",
        "/midwest express clinic/i",
        "/quest diagnostics/i",
    ],
    leisure: [
        "/alpine valley/i",
        "/uber(\\s{2,}|\\s+trip|\\.com)/i",
        "/atm withdrawal/i",
        "/chicago architect/i",
        "/chestnut mountain/i",
        "/chicago park distr/i",
        "/zelle.*to p/i",
    ],
    travel: [
        "/air canada/i",
    ],
    projects: [
        "/google\\*cloud/i",
        "/amazon web services/i",
        "/google \\*services/i",
        "/google \\*domains/i",
        "/google\\*domains/i",
    ],
    duplicates: [
        "/balance forward/i",
        "/virement/i",
        "/payment (received|.*thank you|to.*card)/i",
    ],
};
