export const categories = {
    keyboards: [
        "NOVELKEYS",
        "KEBO.STORE",
        "Cephalopod",
        "LILLEKRYDDE",
        "MASSDROP",
        "THEKEY.COMPANY",
        "DIXIE MECH",
        "NICETECHNOL",
        "RINGERKEYS.COM",
        "TX KEYBOARDS",
        "PRIME KEYBOARDS",
        "ALIEXPRESS",
        "Archetype",
        "ARCHETYPE",
        "Rama Works",
        "RAMAWORKS",
        "TOKYOKEYBOARD",
        "MALVIX",
        "SPACECABLES",
        "CEPHALOPODC",
        "Nice Technologies",
        "ZEAL GENERATION",
        "Valvik",
        "Zhantu Huang",
        "Zap Cables",
        "ZAP CABLES",
        "DROP.COM",
        "ACE KEYBOARD",
        "TEAL TECHNIK",
        "ORIGINATIVE",
        "SMPL SUPPLY",
        "CFTKB",
        "Unicomp, Inc.",
        "PROJECTKB",
        "GLORIOUS PC",
        "Mechanical Keyboards Inc",
        "M KEYBOARDS",
        "PIKATEA",
        "*3334186279",
        "STUPIDFISH",
    ],
    shopping: [
        "AMZN Mktp",
        "Amazon.com*",
        "BESTBUY",
        "FORMD",
        "TARGET",
        "INDIEGOGO",
        "DBRAND",
        "Facebook Technologies",
        "FACEBOOKTEC OCULU",
        "POCKET-TRIPOD-PRO",
        "TOPO DESIGNS",
        "MICROCENTER",
        "MICRO CENTER",
        "VANS INC",
        "Vans Inc",
        "DBA A Chip Off The Old Block Toys",
        "DBACHIPOFFO",
        "IKEA.COM",
        "eBay",
    ],
    games: [
        "Riot",
        "ORIGIN.COM",
        "STEAMGAMES.COM",
        "Steamgames.com",
        "Steam Purchase",
        "Bumble",
        "BUMBLE",
        "MOJANG",
        "Kinguin",
        "KINGUIN",
        "Sirvo LLC",
        "Red Apps",
        "Nadav Fima",
    ],
    food: [
        "FRESHLY",
        "SOUTH LOOP MARKET",
        "JEWEL OSCO",
        "DUNKIN",
        "H MART",
        "WALGREENS",
        "Giordano's",
        "GIORDANO'S",
        "SHAKE SHACK",
        "MCDONALD'S",
        "FEDERALES",
        "POPEYES",
        "Amazon Tips",
        "Freshly",
        "UBER EATS",
        "LUKE'S",
        "ALTHEA",
        "CITY TAP",
        "VIVI BUBBLE TEA",
        "CRAFT PIZZA",
        "PEPSIVEN",
        "CESCAS",
        "DO-RITE",
        "CALIFORNIA FOOD MART",
        "WELCOME BACK LOUNGE",
        "CVS/PHARMACY",
        "NOODLES ETC",
        "TIKKA N  CURRY",
        "DOMINO'S",
        "HAROLD'S",
        "MOTHERS CHICAGO",
        "FULTON MARKET LOCAL",
        "VENMO",
        "TEAMO BOBA",
        "GIORDANOS",
        "SANGAMON CHICAGO",
        "CHIPOTLE",
        "LA FOURNETTE",
        "VANILLE",
        "7-ELEVEN",
        "THE MONKEY'S PAW",
        "1LNCLN PRK",
        "BURGER KING",
    ],
    housing: ["Quick", "Jin's"],
    finances: [
        "VANGUARD",
        "Autosave",
        "Dividend",
        "Employer Contribution",
        "Interest",
        "Investment: V",
    ],
    fees: [
        "FOREIGN EXCHANGE RATE ADJUSTMENT",
        "HEALTHEQUITY INC",
        "DOMESTIC INCOMING WIRE FEE",
        "FOREIGN TRANSACTION FEE",
    ],
    income: [
        "GOOGLE LLC",
        "DEPOSIT",
        "Nacho",
        "TPS",
        "IMPOT SOLIDARITE",
        "TAX REF",
        "FEDWIRE CREDIT",
        "MORGAN STANLEY S DIR CREDIT",
        "MORGAN STANLEY S DIR PAYMENT",
        "MORGAN STANLEY S PAYMENT",
        "Morgan Stanley   ACH CREDIT",
    ],
    subscriptions: [
        "Amazon Prime",
        "Patreon",
        "NETFLIX.COM",
        "Netflix.com",
        "GITHUB",
        "Disney Plus",
        "AGILEBITS",
        "AgileBits",
        "1Password",
        "1PASSWORD",
        "The New York Times Co.",
        "NEW YORK TIMES",
        "NYTIMES",
        "Average Tech Reviews",
        "AVERAGE TECH REVI",
        "Google Storag",
    ],
    utilities: [
        "COMM ED",
        "COMED",
        "VENTRA",
        "USPS CHANGE OF ADDRES",
        "Google Fi",
        "GOOGLE FI",
        "STATE FARM",
        "HAIR CUTTERY",
        "SUPERCUTS",
        "BELL MOBILITY",
        "MIDWEST EXPRESS CLINIC",
        "QUEST DIAGNOSTICS",
    ],
    leisure: [
        "ALPINE VALLEY",
        "UBER  ",
        "UBER.COM",
        "UBER TRIP",
        "ATM WITHDRAWAL",
        "CHICAGO ARCHITECT",
        "CHESTNUT MOUNTAIN",
        "Chicago Park Distr",
    ],
    travel: ["AIR CANADA"],
    projects: [
        "GOOGLE*CLOUD",
        "Amazon Web Services",
        "GOOGLE *SERVICES",
        "GOOGLE *Domains",
        "GOOGLE*DOMAINS",
    ],
    duplicates: [
        "Balance Forward",
        "Payment to Chase card",
        "Payment Thank You",
        "Virement",
        "PAYMENT - THANK YOU",
        "PAYMENT RECEIVED",
    ],
    // Fallback if no other category matches.
    other: [],
};
